### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by freshface** [aerni/statamic-snipcart#12]
Got this error if i want to add a new product.

Clean statamic install.

```
Statamic 3.2.33 Solo
Laravel 8.83.1
PHP 7.4.23
aerni/snipcart dev-master
```
Did: composer require aerni/snipcart

Error: https://flareapp.io/share/dmkjaXe5#F87

**Comment by freshface** [comment]
If i remove the categories taxonomies from the product blueprint an save.
It is fixed. The original blueprint need some changes, see: https://jmp.sh/ADATQAG

**Comment by FlorianMoser** [comment]
The same issue is with the "taxes" taxonomy. You will have to update this as well in the product blueprint.

**Comment by aerni** [comment]
Thanks for reporting this. I'm aware of the issue. I will have to do some refactoring to support PHP 8 and Statamic 3.3. I'm swamped at the moment but am going to work on this as soon as possible.
