### ISSUE TITLE
Unable to save

### ISSUE THREAD

**Issue by FlorianMoser** [aerni/statamic-snipcart#15]
A new entry cannot be saved in the collections/products collection. Just install a new Statamic project (v3.3.12) and install aerni/snipcart. Create a new entry and save it. Nothing happens. No error, no log, no console log. There isn't even an HTTP request.

**Comment by aerni** [comment]
This addon is not yet compatible with Statamic 3.3. That's why you're encountering those issues. I will make it compatible as soon as I get to it. Thanks for reporting!
