### ISSUE TITLE
Idea: Custom Variant Builder

### ISSUE THREAD

**Issue by aerni** [aerni/statamic-snipcart#3]
I'm thinking about adding a custom variant builder to allow for more granular control of variants. Something similar to [Shopify's variant builder](https://www.youtube.com/watch?time_continue=113&v=UUIP1n_9kP8&feature=emb_logo).

I will only add this feature if there's enough demand. Upvote this issue, if you have need for this.

**Comment by DeysonOrtiz** [comment]
@aerni It seems the video you had linked is set to private. 😞

**Comment by aerni** [comment]
Yeah, it looks like Shopify set it to private …
