### ISSUE TITLE
Invalid Argument Exception Error appears

### ISSUE THREAD

**Issue by DeysonOrtiz** [aerni/statamic-snipcart#5]
Hello and good day.

I had wanted to test your add on but when I run your install command I recieve this message on my local system:

```
 [InvalidArgumentException]
  Package aerni/snipcart has a PHP requirement incompatible with your PHP ver
  sion, PHP extensions and Composer version
```

I have PHP 8.0.2 and I installed composer 

Please let me know what you think. 🤔
Thank you and have an amazing day! 😊

**Comment by aerni** [comment]
This addon doesn't yet work with PHP 8. I will add support soon.

**Comment by DeysonOrtiz** [comment]
@aerni   Thank you. 🙂
Should I try to downgrade or wait for the update?

Thank you and have an amazing day! 😊

**Comment by aerni** [comment]
If you don't depend on PHP 8, I'd downgrade to PHP 7.4.

**Comment by DeysonOrtiz** [comment]
Done.  

Found this great tutorial on how to switch PHP in case anyone else needs it:  https://getgrav.org/blog/macos-bigsur-apache-multiple-php-versions

**Comment by aerni** [comment]
I added support for PHP 8 in the latest master.
