### ISSUE TITLE
Uninstall through CLI

### ISSUE THREAD

**Issue by DeysonOrtiz** [aerni/statamic-snipcart#7]
Hello and good day.

Is there a way to completely uninstall your Add-On through Command Line.  I would like to uninstall it and then re-install it to make sure it is installed correctly.
It seems the Uninstll through Control Panel is not working.

Thank you and have an amazing day! 😊

**Comment by aerni** [comment]
Run `composer remove aerni/snipcart` to uninstall the addon. You will have to manually delete your collections, taxonomies, and the addon's config though.

**Comment by DeysonOrtiz** [comment]
Thank you. 🙂
