### ISSUE TITLE
Installation fail with php 8.0.3 

### ISSUE THREAD

**Issue by fredbouin** [aerni/statamic-snipcart#8]
With PHP 8.0.3 and composer 2.0.9 I get the error:
  
  Package aerni/snipcart at version dev-master has a PHP requirement incompat  
  ible with your PHP version, PHP extensions and Composer version

**Comment by aerni** [comment]
Ok. It looks like the dependency [jordanbrauer/unit-converter](https://github.com/jordanbrauer/unit-converter) is not yet compatible with PHP 8.  You'll have to settle with PHP 7.4 for now.

I tested a fresh install on PHP 7.4 and can't reproduce the error you're describing. Make sure to install from like this `composer require aerni/snipcart:dev-master`.

**Comment by aerni** [comment]
Cool!
